### ISSUE TITLE
API 문서 작성

### ISSUE THREAD

**Issue by goormdev** [likelion11-kangwon/duri#9]
전체적인 프레임워크에 대한 API 문서 작성이 필요해보입니다.

**Comment by goormdev** [comment]
API 문서를 자동 생성하도록 하는 것도 좋을 것 같습니다.
참고: https://typedoc.org/

또한 프레임워크 분리 후 문서화 해도 될 것 같습니다.

**Comment by cstria0106** [comment]
commit a1592bbbda34d0ff31b0c8bae82749da820c8b66 solved this issue
